### ISSUE TITLE
Chart width is very small after selecting a player spot

### ISSUE THREAD

**Issue by Rippsy** [Anoromi/bar-stats#1]
To reproduce:

1. Search any map/results combo
2. Click a spot
3. Click Combined OS
4. Click Winrates

Expect result
![image](https://github.com/user-attachments/assets/c9c02c67-454c-4a2a-8600-a3c777e14974)

Actual result
![image](https://github.com/user-attachments/assets/47eeef21-e465-4a60-8284-01d3b2fc91de)

**Comment by Anoromi** [comment]
Should be fixed in new version.
