### ISSUE TITLE
Koom Valley merges front 2 spots into 1, showing only 7 spawns

### ISSUE THREAD

**Issue by Rippsy** [Anoromi/bar-stats#3]
![image](https://github.com/user-attachments/assets/c8a095e3-7672-4fac-aa96-03c8c1031890)

Issue also present on:
Nuclear Winter
Salmiakki

**Comment by Anoromi** [comment]
This shouldn't be a problem now on most maps. However, currently, in some cases like Salmiakki the opposite happens: positions are split up in 2. Any changes would require complex rewrites, so for now the issue will be ignored.
